services:
  db:
    image: postgres:14
    container_name: shop_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shopdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shop-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: shop_backend
    environment:
      DATABASE_URL: postgres://user:password@db:5432/shopdb
      JWT_SECRET: super_secret_key
      REFRESH_SECRET: another_super_secret_key
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ../backend:/app
      - /app/node_modules
    networks:
      - shop-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: shop_frontend
    environment:
      REACT_APP_API_URL: http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ../frontend:/app
      - /app/node_modules
    networks:
      - shop-network

volumes:
  pgdata:

networks:
  shop-network:
    driver: bridge
